# default configuration
baseURL = "https://incubusz.github.io/pakdiuhuh"
publishDir = "docs"
theme = "kross"
title = "pakdiuhuh | hugo portfolio"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 2

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5


# default parameters
[params]
home = "Home"
logo = "images/logo.png"
# theme color
theme_color = "#ff5252"
# contact info
phone = "+62 838 7726 0520"
email = "pakdiuhuh@gmail.com"
address = "Indonesia, jawabarat, bogor barat"
# meta description
author = "pakdiuhuh"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 pakdiuhuh"


# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format
